"""empty message

Revision ID: 5b90dbbb44fd
Revises: 13f8884888d6
Create Date: 2026-09-24 12:47:04.228083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b90dbbb44fd'
down_revision = '13f8884888d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folha', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folha', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###
